"""Add age attribute to User model

Revision ID: 117352624590
Revises: 
Create Date: 2024-11-23 18:29:45.028857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117352624590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicerequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_date', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicerequest', schema=None) as batch_op:
        batch_op.drop_column('service_date')

    # ### end Alembic commands ###
